export const TODO = {
  FETCH_TODO_PENDING: 'FETCH_TODO_PENDING',
  FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
  FETCH_TODO_FAILED: 'FETCH_TODO_FAILED',
  CRAETE_TODO_PENDING: 'CRAETE_TODO_PENDING',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILED: 'CREATE_TODO_FAILED',
};
